name:                dom-events
version:             0.0.0.4
github:              "meeshkan/haskell-dom-events"
license:             BSD3
author:              "Mike Solomon"
maintainer:          "mike@meeshkan.com"
copyright:           "2020 Mike Solomon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/meeshkan/haskell-dom-events#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  dom-events-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dom-events
